### ISSUE TITLE
moviemaker.rb fails on GoogleDrive.login

### ISSUE THREAD

**Issue by danrademacher** [nerdsfornature/changebrackets#7]
I just tried to make a movie from the Rim Fire images at request of USFS, and it looks like the changes @kueda made to `fireslurp.rb` for oauth maybe need to happen in `moviemaker.rb` too.

Error looks like this:
```bash
moviemaker.rb:91:in `download_images': undefined method `login' for GoogleDrive:Module (NoMethodError)
	from moviemaker.rb:200:in `<main>'
```

[Line 91](https://github.com/nerdsfornature/changebrackets/blob/master/moviemaker.rb#L91):
```ruby
  session = GoogleDrive.login(GOOGLE_EMAIL, GOOGLE_PASSWORD)
```

I suspect the changes to fireslurp.rb in [this commit](https://github.com/kueda/changebrackets/commit/627baa0c3e43e5cc9140237782dcc4d48fc8e86d#diff-fcd8c7640a608d978e2a6f9b66e1bef2) need to be done in `moviemaker.rb` as well (or some variation of same)

**Comment by danrademacher** [comment]
I think I've got this working locally. Will verify and commit if so

**Comment by kueda** [comment]
Did it work? Sorry I didn't fix this when I fixed the other script.

**Comment by danrademacher** [comment]
I have the auth working -- but it doesn't seem to download the same number of images each time, and then I was getting an error after it "finished" downloading. Ran out of time and energy over the weekend but didn't want to commit only partially working code. I'll get more info and post before the night is out

**Comment by danrademacher** [comment]
OK, pretty sure auth fixed in this branch: https://github.com/nerdsfornature/changebrackets/tree/moviemaker-fix

@kueda could you give it a try and verify? I am getting other errors _after_ auth and download of images but I think that's more evidence that I never ran this script before and maybe I'm missing dependencies or something

**Comment by kueda** [comment]
Yeah, running into an issue with @pglotov's alignment script, which means it would need to be rebuilt with a recent version of opencv... which might not work. I've since discovered http://wiki.panotools.org/Align_image_stack, which might be a better solution to the alignment problem, but it's a bit fussy and will need some tweaking before it will work (right now it just segfaults on me when run with default settings).

**Comment by jasper2xF** [comment]
I also had problems with the GoogleDrive access. Using the up-to-date authentication as in fireslurp.rb fixed this for me. Looks like exactly what @danrademacher did.

Also note that I raised issue #9 in relation to the alignment script being deprecated.
